# Site settings
title: "CodePit"
description: >

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: Thilip Varadharajan
  googleplus: 
  github: thuruv
  twitter: @silverbullet52x
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
