# Site settings
title: "CodePit"
description: "None Provided by authour as he thinks you are obviously a moron."


baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: Thilip Varadharajan
  googleplus: 
  github: thuruv
  twitter: silverbullet52x
  # disqus: your_disqus_username

 google_analytics: 'UA-152757977-1'

# Build settings
markdown: kramdown
